---
- name: Web Server Configuration with Handlers
  hosts: webservers
  remote_user: ansible
  become: true
  vars:
    web_port: 80
    server_name: "{{ ansible_fqdn }}"

  tasks:
    - name: 'Install nginx on FreeBSD'
      package:
        name: nginx
        state: present

    - name: Start nginx service
      service:
        name: nginx
        state: started
        enabled: yes

    - name: 'Deploy nginx configuration for FreeBSD'
      template:
        src: nginx-freebsd.conf.j2
        dest: /usr/local/etc/nginx/nginx.conf
        backup: yes
      when: ansible_os_family == "FreeBSD"
      notify: restart nginx

    - name: 'Deploy nginx configuration for OpenBSD'
      template:
        src: nginx-openbsd.conf.j2
        dest: /etc/nginx/nginx.conf
        backup: yes
      when: ansible_os_family == "OpenBSD"
      notify: restart nginx

    - name: 'Deploy nginx configuration for NetBSD'
      template:
        src: nginx-netbsd.conf.j2
        dest: /usr/pkg/etc/nginx/nginx.conf
        backup: yes
      when: ansible_os_family == "NetBSD"
      notify: restart nginx

    - name: Verify nginx configuration
      command: nginx -t
      register: nginx_config_test
      changed_when: false
      failed_when: nginx_config_test.rc != 0

    - name: Display configuration test result
      debug:
        msg: "Nginx configuration test: {{ 'PASSED' if nginx_config_test.rc == 0 else 'FAILED' }}"

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
      listen: "restart nginx"

    - name: reload nginx
      service:
        name: nginx
        state: reloaded
      listen: "reload nginx"
