---

- name: Install php
  package:
    name: php
    state: present

- name: Install nginx
  package:
    name: nginx
    state: present

- name: Copy application
  template:
    src: "{{ item }}"
    dest: "/var/www/html/{{ item }}"
  loop:
    - roles-example.php
  notify:
    - restart nginx
